name: Bug Report
description: Report a reproducible bug or unexpected behavior.
title: "[Bug]: "
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: what-happened
    attributes:
      label: What happened?
      description: Please describe the bug in detail.
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the bug?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true
  - type: input
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, browser, Node version, etc.
    validations:
      required: false 